### ISSUE TITLE
Remove MeasureFunc

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#101]
[This](https://github.com/DioxusLabs/sprawl/blob/8f72a707eb069d7d324096c7405b383f8245f25d/src/node.rs#L14) is an unclear, overengineered abstraction.

We should re-architect to avoid it completely.

It also causes usability headaches, as seen in #57.

**Comment by colepoirier** [comment]
Ah just saw the controversial label. I was hoping this would be a trivial pr. What is involved in the rearchitecting of the library to remove the MeasureFunc?

**Comment by alice-i-cecile** [comment]
So, first off is understanding how exactly this is being used. I *think* it's just used for unit conversions.

If that's the case, we should be able to replace it with some trait magic. My gut instinct is that we can just replace this with an `Into<Dimension>` or the like, but it needs further investigation.

Some inherited docs would have been nice; the approach used in `MeasureFunc` is extremely unusual and there's no obvious reason why it needs to be that way. But maybe we're missing something!

**Comment by alice-i-cecile** [comment]
Ah, some clues: this is inherited from other implementations maybe? In languages that don't have traits?

1. Incidental mention: https://blog.kowalczyk.info/article/9/tutorial-for-github.comkjkflex-go-package-implementation-of-css-flexbox-algorithm.html
2. Some very helpful docs /s: https://github.com/kjk/flex/blob/ed34d6b6a425cc6c1b76e224b0c882d608c12aaa/yoga_h.go#L28
3. Extremely helpful docs for the Rust binding to Yoga /s: https://docs.rs/yoga/latest/yoga/types/type.MeasureFunc.html
4. Some possibly relevant `MeasureMode` options?: https://docs.rs/yoga/latest/yoga/types/type.MeasureFunc.html
5. `YGNodeSetMeasureFunc` (the name of the related method in Yoga) closed issue: https://github.com/facebook/yoga/issues/959
6. Search results in `yoga`: https://github.com/facebook/yoga/search?q=measurefunc

Searching the [spec](https://www.w3.org/TR/css-flexbox-1/) for measure turns up nothing :/ @andriyDev, any chance you can point us to some useful docs, or at least explain what you've been using this for?

**Comment by alice-i-cecile** [comment]
Aha: Visly had some docs [buried in their very non-standard docs](https://vislyhq.github.io/stretch/docs/rust/).

Basically it seems like `MeasureFunc` is used for the computation of intrinsic size. Each node may have their own strategy for this:

> Set/Get the measure function on a node. This function will be called on leaf nodes to resolve the instrinsic size of the node given a set of constraints.

**Comment by alice-i-cecile** [comment]
Poking at this, this actually appears to be impacted by https://github.com/rust-lang/rust/issues/29625, of all things. We need to pass in a function and then call it, but we cannot call functions if we only have a reference to it because [`Fn::call`](https://doc.rust-lang.org/std/ops/trait.Fn.html#tymethod.call) is unstable (for the indefinite future).

I hate this whole design a lot. My failed prototype in this direction, to replace the `MeasureFunc` enum directly with a boxed trait object:

```rust
#[doc(alias = "MeasureFunc")]
/// A trait that allows nodes to use a custom strategy to determine their size
///
/// Each node may have a unique strategy.
pub trait Measurable: Send + Sync + 'static {
    /// The function used to determine the size of this node
   // We cann
    fn compute_intrinsic_size(self, starting_size: &Size<Option<f32>>) -> Size<f32>;
}

impl<F: Send + Sync + 'static + Fn(&Size<Option<f32>>) -> Size<f32>> Measurable for F {
    fn compute_intrinsic_size(self, starting_size: &Size<Option<f32>>) -> Size<f32> {
        self(starting_size)
    }
}
```

**Comment by alice-i-cecile** [comment]
Right: they can't just store a boxed trait object in `NodeData` because they're trying to make this crate work in an allocation-free environment.

We could make `NodeData` generic over the `MeasureFunc` used, but that will result in some *interesting* type erasure / type reflection nonsense to get working, as we would need to store a vector-like of distinct types without using any boxes.

I'm reluctant to attempt this nonsense before moving to a real ECS in #130.

**Comment by alice-i-cecile** [comment]
Consolidating discussion in #57.
