### ISSUE TITLE
Add index checks to Sprawl::remove_child_at_index and related methods

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#104]
See [this todo](https://github.com/DioxusLabs/sprawl/blob/8f72a707eb069d7d324096c7405b383f8245f25d/src/node.rs#L172). We want to return an error, rather than panicking.

This is related to issue #100, and can probably be tackled at the same time.

**Comment by TheDestroyer19** [comment]
I'd like to tackle this issue

**Comment by alice-i-cecile** [comment]
All yours :) Feel free to open a draft PR if you run into any difficulties.

**Comment by alice-i-cecile** [comment]
Fixed in #152.
