### ISSUE TITLE
Consider removing Dimension::Undefined

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#114]
My instincts suggest this should be an `Option<Dimension>`.

**Comment by nicoburns** [comment]
@alice-i-cecile @Weibye I might be being stupid, but doesn't this change (replacing Dimension::Undefined with Option<Dimension>) effectively undo the earlier change of making `Dimension::Auto` the default dimension? If this change is made, then the default will now effectively be `Option::None` (= Dimension::Undefined).

**Comment by Weibye** [comment]
Good thing to flag but I think it should be solved by having the default `FleboxLayout` values be `Some(Dimension::Auto)`, and every variable / parameter that previously used `Dimension::Undefined` should now have the `Option<Dimension>` type.

You can see the current state of this over at #188 (and please leave a review)

It could be that changing these default values is what is causing the tests to fail. I haven't been able to get to the bottom of that yet so extra eyes would be appreciated :)

**Comment by nicoburns** [comment]
Implemented in #269
