### ISSUE TITLE
Identify or implement step 4 of the flex layout algorithm

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#119]
## What problem does this solve or what need does it fill?

Currently, [step 4](https://www.w3.org/TR/css-flexbox-1/#algo-main-container) of the flex layout algorithm is not explicitly documented. This can mean that the documentation is missing or that the step is not yet implemented.
Since we want to adhere to the specs wherever possible, we need to make sure that we have this step and that documentation explains what it does.

## What solution would you like?

- If the step is implemented, move it to a separate function if possible, document the function similar to the other ones with links to [the spec](https://www.w3.org/TR/css-flexbox-1/#algo-main-container).
- If the step is not yet implemented, implement it with docs as explained above.

## What alternative(s) have you considered?

If the step is not applicable for whatever reason, this still needs to be documented explicitly.

## Additional context

Originally discussed in #39.

**Comment by nicoburns** [comment]
Closing this as this step is actually done earlier in "compute constants" in our implementation. #317 updates the comments to point this out.
