### ISSUE TITLE
Fix `min_max` computation when resolving flexible lengths to follow the spec

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#122]
## What problem does this solve or what need does it fill?

The `min_max` computation when resolving flexible lengths seems to not follow the spec:
<https://github.com/DioxusLabs/sprawl/blob/11701ee97d68b22a231cac081aab4308af136706/src/flexbox.rs#L669-L675>

## What solution would you like?

The computation should follow the spec. Otherwise, the computation should probably be refactored.

## What alternative(s) have you considered?

If it works, we could keep it as-is. Probably a bad idea though.

## Additional context

Originally discussed in #39.

**Comment by Weibye** [comment]
> If it works, we could keep it as-is. Probably a bad idea though.

I agree that this should be fixed. Keeping these 'ghosts' in the code makes it harder to maintain and understand where things go wrong

**Comment by nicoburns** [comment]
I believe this one was also fixed as part of #291
