### ISSUE TITLE
Fix setting of children main size in flex length resolving to follow the spec

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#123]
## What problem does this solve or what need does it fill?

Setting the main size of the children when resolving the flexible lengths does not seem to follow the specification:
<https://github.com/DioxusLabs/sprawl/blob/11701ee97d68b22a231cac081aab4308af136706/src/flexbox.rs#L519-L522>

## What solution would you like?

The implementation should be adjusted to follow the specification and refactored if necessary.

## What alternative(s) have you considered?

If it works we could also leave it as-is.

## Additional context

Originally discussed in #39.

**Comment by nicoburns** [comment]
This was fixed in #294
