### ISSUE TITLE
Create more robust benchmarks

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#128]
Before tackling more serious performance changes, I would like a wider array of benchmarks, each focused on either a realistic scenario or a particular way we could stress the algorithm.

**Comment by TimJentzsch** [comment]
One option to generate bigger benchmarks would be to use [seedable RNG](https://docs.rs/rand/latest/rand/trait.SeedableRng.html) to pseudo-randomly generate big (but reproducable) notes that can be benchmarked.

**Comment by alice-i-cecile** [comment]
The benchmarks for yoga appear to be [here](https://github.com/facebook/yoga/blob/578d197dd6652225b46af090c0b46471dc887361/javascript/tests/Benchmarks/YGBenchmark.js). I'd love to do a head-to-head.

**Comment by Weibye** [comment]
I wonder if it would be useful to setup benchmarks for each of the proposed ui-"archetypes" listed here: https://github.com/bevyengine/bevy/issues/1974

It could inform us of more detailed "what type of layout suffers what kind of bottlenecks". 

Though I'm not fully sure how to best go about setting something like that up.

**Comment by alice-i-cecile** [comment]
It's a good idea, but I think best left to later. If we can produce real layouts in upstream applications like `bevy`, we can test them in practice rather than trying to make a best guess.

**Comment by Weibye** [comment]
Aye, good point
