### ISSUE TITLE
Inline small functions

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#129]
There are a massive number of tiny helper functions in this library that are not marked `#[inline]`. We should see if doing so has a measurable effect on the benchmarks.

**Comment by Sheepyhead** [comment]
I went ahead and attempted this, see https://github.com/Sheepyhead/taffy/tree/test-inline for details.
The benchmarks seem to suggest a slight regression in performance with these changes, at best we see no regression and a slight reduction in variance for the upper bound of time spent, see attached graphs where RED is the benchmark without the inline changes and BLUE is the benchmark with more functions inlined
## Generated benchmark
![image](https://user-images.githubusercontent.com/15895891/174083934-5865e2e8-8f07-4f70-bd16-139cc197775b.png)
## Deep hierarchy build benchmark 
![image](https://user-images.githubusercontent.com/15895891/174084102-c23a81bc-329b-4485-a057-e37026c6c035.png)
## Deep hierarchy relayout benchmark
![image](https://user-images.githubusercontent.com/15895891/174084223-0ce9a1cb-abd6-4a99-ad97-5570d19aab1f.png)
## Deep hierarchy single benchmark
![image](https://user-images.githubusercontent.com/15895891/174084308-24ef4d62-d853-4983-90d8-c0f123b1f89e.png)

**Comment by alice-i-cecile** [comment]
Nice work. I'm going to close this out as "does not help" for now; we can try again in the future once we have more benchmarks and profiling set up.
