### ISSUE TITLE
Consider migrating to a lightweight ECS framework

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#130]
The code in Forest is effectively a very poorly optimized ECS, attempting to store tabular structs-of-arrays. We should consider just using an ECS framework and seeing what sort of performance gains we can get.

In particular, the data storage is extremely suboptimal, with relatively large "components" being accessed constantly when only a single field is needed.

**Comment by Weibye** [comment]
Would you consider `bevy_ecs` as lightweight in this context?

**Comment by alice-i-cecile** [comment]
Maybe. For the purposes of Bevy, obviously yes. For Dioxus, I'd want to defer to @jkelleyrtp. We may want to make an issue to Bevy to split out `bevy_ecs` into a more useful set of feature flags to help keep it minimal. We don't need any of the system scheduling here for example.

`hecs` would be my other choice.

**Comment by jkelleyrtp** [comment]
> Maybe. For the purposes of Bevy, obviously yes. For Dioxus, I'd want to defer to @jkelleyrtp. We may want to make an issue to Bevy to split out `bevy_ecs` into a more useful set of feature flags to help keep it minimal. We don't need any of the system scheduling here for example.
> 
> `hecs` would be my other choice.

I've enjoyed hecs but have not used bevy_ecs. If bevy_ecs is pretty big, then either we could punt this work until bevy_ecs is trimmed down with the right flags or start with hecs and then move to bevy_ecs when it's similarly thin.

**Comment by alice-i-cecile** [comment]
Yeah, I think start with `hecs` and then consider migrating over once it has flags. We should wait for more code quality fixes and unit tests first though before tackling this.

**Comment by alice-i-cecile** [comment]
Will be closed by #196, which solves the same problems with a slotmap.
