### ISSUE TITLE
Remove outdated tags from repo; replace with correct tag for `0.1.0` release

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#136]
There are currently two tags in the repo which refer to old releases of `stretch`.

It would be preferable to remove them as they are currently ~~misleaning~~ misleading

**Comment by alice-i-cecile** [comment]
@jkelleyrtp I don't have permissions to modify these; I think that this is something that a member of @DioxusLabs needs to do.

**Comment by jkelleyrtp** [comment]
@alice-i-cecile I think you should be able to - at least it wasn't obvious for me on how to do it without visiting the tags themselves. I've removed the two and am adding a release for 0.1.0

<img width="1312" alt="Screen Shot 2022-06-22 at 10 52 23 PM" src="https://user-images.githubusercontent.com/10237910/175196951-1c9f3939-04eb-4f06-ab03-19505d533658.png">
