### ISSUE TITLE
Change `width` and `height` of `Size` to `Option<T>` instead of `T`

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#154]
## What problem does this solve or what need does it fill?

The `geometry::Size<T>` is currently defined as
```rs
pub struct Size<T> {
    /// The x extent of the rectangle
    pub width: T,
    /// The y extent of the rectangle
    pub height: T,
}
```

While digging through the code in relation to #144 and #148 I've started wondering if we should change the definition of `Size` to the following:

```rs
pub struct Size<T> {
    /// The x extent of the rectangle
    pub width: Option<T>,
    /// The y extent of the rectangle
    pub height: Option<T>,
}
```

The width and height fields need to be independently defined or not, which means that replacing everything with `some_field: Option<Size>` will not cover all use-cases throughout the code. 

I'm not yet able to see the full picture how everything fits together once we:
`Dimension::Undefined` -> `Option<Dimension>` 
`Number::undefined` -> `Option<f32>`

but it seems it is a must for this to work (?)

## What alternative(s) have you considered?

Leave it as is, but I expect it to change in some way or another. 

Are there alternative designs we can explore?

**Comment by alice-i-cecile** [comment]
This seems like about the right approach. IN general it really seems like we're typically storing options here.

**Comment by alice-i-cecile** [comment]
I'm tackling this now.

**Comment by alice-i-cecile** [comment]
Actually, this appears to be blocked on #148. @Weibye, feel free to attempt this in a follow-up, or bug me to do it :)

**Comment by Weibye** [comment]
> Actually, this appears to be blocked on #148. @Weibye, feel free to attempt this in a follow-up, or bug me to do it :)

First I thought we'd need so solve #148 before this, then I thought this needed to come first. I supsect they both need to be done at the same time for the whole system to work, but I'll keep tinkering with it tomorrow morning :)

**Comment by nicoburns** [comment]
This doesn't won't work now we're also using `Size` with `AvailableSpace`. And `Size<Option<f32>>` is working well as is :)

**Comment by Weibye** [comment]
👍 It seemed to make sense at the time :)
