### ISSUE TITLE
Create head-to-head benchmarks with yoga

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#166]
[yoga](https://yogalayout.com/) is Facebook's flexbox library.

They have a set of benchmarks [here](https://github.com/facebook/yoga/blob/578d197dd6652225b46af090c0b46471dc887361/javascript/tests/Benchmarks/YGBenchmark.js)  I'm curious to see how we compare directly, and this could be a solid marketing point if / when we perform well.

This issue is spun out from #128 to split the scope more appropriately.

**Comment by alice-i-cecile** [comment]
Basically fixed: 
> > This is actually now at least partially implemented in `benches/big_tree.rs`. We are running several variants of yoga's "huge nested layout" with various node counts, including 10,000 which is what they benchmark. They have a couple of other benchmarks, but they seem too small to be interesting to me.

**Comment by nicoburns** [comment]
Reopening this, as I've recently updated the `yoga` crate ([yoga-rs](https://github.com/bschwind/yoga-rs)) to the latest version of Yoga, which means that actual head-to-head benchmarks is now feasible.

I would suggest that:
- We use criterion's [comparing functions](https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html) functionality to compare Taffy with yoga (via yoga-rs) head-to-head.
- Yoga benchmarks are split out of `big_bench.rs` into their own `yoga.rs` file
- At least to start, we use yoga's "huge nested benchmark" as the basis of our benchmarks. This is already implemented for taffy in  `big_bench.rs`, but will need to be implemented for `yoga-rs`.
- We benchmark 4 variants:
  - Computation only (1,000 nodes)
  - Computation only (10,000 nodes)
  - Tree creation and computation (1,000 nodes)
  - Tree creation and computation (10,000 nodes)
  
  @TimJentzsch Perhaps you'd be interested in taking this on again?

**Comment by TimJentzsch** [comment]
When I have enough time I'll try to tackle this :)
