### ISSUE TITLE
compute_constants is not using the `height` of the parent for sizes

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#183]
## `taffy` version

Current `main`

## What

I can't tell if this is a bug or not so I need additional eyes on this:
During `compute_constants` we are applying only the `width` of the parent, and not the `height`. 

To correctly compute the `Rect<f32>` of margin, padding, border I would expect both width and height of the parent to be included in the mix. 

https://github.com/DioxusLabs/taffy/blob/main/src/flexbox.rs#L220-L222

I suspect it is a bug that just does not show up in a test anywhere (yet)

**Comment by Weibye** [comment]
I tried fixing this over at #184 and there are 3 tests that fail: 
```
test: percentage_margin_should_calculate_based_only_on_width
test: percentage_multiple_nested_with_padding_margin_and_percentage_values
test: percentage_padding_should_calculate_based_only_on_width
```
which strongly suggest I'm wrong and this is by design.

I'm going to try digging a bit more into the specs to get some understanding into why this is the case.

**Comment by Weibye** [comment]
Closing this for now, will reopen later if turns out to be a bug

**Comment by mamekoro** [comment]
Here are some references for those who have similar questions.

> The percentage is calculated with respect to the width of the generated box's containing block. Note that this is true for 'margin-top' and 'margin-bottom' as well.
>
> ― https://www.w3.org/TR/CSS2/box.html#margin-properties

> The percentage is calculated with respect to the width of the generated box's containing block, even for 'padding-top' and 'padding-bottom'.
>
> ― https://www.w3.org/TR/CSS2/box.html#padding-properties
