### ISSUE TITLE
Cleanup inconsistent convention of `Rect` fields

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#187]
The fields of `Rect` should either be `main_start, main_end, cross_start, cross_end` or `left, right, top, bottom` but not a mix of the two.

Most likely the latter

_Originally posted by @Weibye in https://github.com/DioxusLabs/taffy/issues/118#issuecomment-1153124824_

**Comment by alice-i-cecile** [comment]
I think the latter is preferred here; this will make it much easier to reuse across layout algorithms.
