### ISSUE TITLE
Nodes can have multiple parents

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#191]
Nodes can currently have multiple parents. Under the no-allocation settings though, the number of parents is limited to one, as reported by @mcrvz in #176.

This creates divergence, but the correct behavior is actually to limit the number of parents to 1 across all platforms (likely by not storing a vec). Multiple parents cannot be defined in HTML, and there is no logical interpration of how style inheritance should work with more than one parent.

This should both improve robustness and performance.

**Comment by alice-i-cecile** [comment]
I'm on board with either approach here :)

**Comment by jkelleyrtp** [comment]
One thing - if we dropped no_std support, we could use slabs for the children Slab. So, a slab of slabs. This would allow us to gain some performance when removing nodes at random.
