### ISSUE TITLE
Remove no-alloc feature set

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#192]
While `no_std` support is relatively painless, fully allocation free layouting is a significant technical burden (we must maintain or import custom data structures, and there are arbitrary limits to the number of children) and lacks clear motivation.

Ordinarily, allocation-free setups are useful for embedded software on extremely limited devices. However, as we are a UI layouting library, it is very unclear who would care about this, or why this feature exists.

If you care about this functionality of `taffy`, please let us know about your use cases! I'll leave this open for several releases, but if we don't hear compelling counterarguments I'm tempted to remove it.

**Comment by Weibye** [comment]
Did some digging: This was the PR that originally added the feature https://github.com/vislyhq/stretch/pull/60

Other than "allows us to run the library without a heap" I'm unable to find any concrete use-cases mentioned where this would be necessary.

**Comment by TimJentzsch** [comment]
There is currently also no way of configuring the maximum number of nodes in `no-alloc`, so it's probably not very useful.

**Comment by alice-i-cecile** [comment]
@mockersf, do you have opinions on this?

**Comment by jkelleyrtp** [comment]
I imagine that either this was added to shrink the size of a .wasm binary or someone had a use case for embedded graphics. Though, I don't think taffy would make sense to run in an embedded context that didn't have a heap.

The most likely explanation was the wasm bindings... but if you want to shrink your wasm binaries there are other ways like smaller allocators and wasm-opt to get a few bytes back.

**Comment by alice-i-cecile** [comment]
Those are both plausible. For performance gains, I'd much rather use #130 to imrpove our allocation strategies and get performance gains for all of our users (without a limitation on the number of nodes).

**Comment by alice-i-cecile** [comment]
@dflemstr, could you speak a little bit about your motivation for your original PR? This appears to have been a community contribution, so perhaps you'll be responsive in a way that the visly team hasn't been.

**Comment by mockersf** [comment]
Maybe to help interoperability with other languages?

**Comment by dflemstr** [comment]
@alice-i-cecile hey, sorry for the delay, I'm bad at monitoring GitHub notifications :)

My motivation for the change was to be able to use `stretch` in an environment where heap allocation is not available, for example on embedded devices (embedded as in bare metal circuits with ~kilobytes of total available memory).

I'm for example using it in this library: https://github.com/dflemstr/emui

**Comment by alice-i-cecile** [comment]
Fascinating; I hadn't expected there to be embedded layout applications.

That's cool enough that I'm happy to leave this in unless it imposes a major maintenance burden in the future.

Closing for now.
