### ISSUE TITLE
Move closures in `final_layout_pass()` to standalone methods

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#200]
## What problem does this solve or what need does it fill?

AFAIK closures aren't really suitable for testing, especially when they are stored in local variables. Moving `let layout_line = | ... |` and `let layout_item = | ... |` to proper methods would allow them to be tested

## Solution

Rework the closures to methods, then add tests to those methods

## Additional context

https://github.com/DioxusLabs/taffy/blob/main/src/flexbox.rs#L1343
https://github.com/DioxusLabs/taffy/blob/main/src/flexbox.rs#L1347

**Comment by alice-i-cecile** [comment]
I think this is also likely to make this code easier to understand.
