### ISSUE TITLE
Readme missing from vendored crate

### ISSUE THREAD

**Issue by duncanrhamill** [DioxusLabs/taffy#217]
## `taffy` version

`0.1.0`

## Platform

Ubuntu 20.04

## What you did

I've used the `cargo vendor` command to allow building my crate in an offline environment. 

## What went wrong

When attempting to build taffy would fail to compile with the following error:

```text
error: couldn't read <CRATE_PATH>/vendor/taffy/src/../README.md: No such file or directory (os error 2)
 --> <CRATE_PATH>/vendor/taffy/src/lib.rs:1:10
   |
1 | #[doc = include_str!("../README.md")]
   |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
```
## Additional information

I suspect that either cargo vendor is reading the `Cargo.toml` and there is a missing `readme = "README.md"` line, or that something is wrong with the published version of the crate.

**Comment by nicoburns** [comment]
I think this will be the `include = ["src/**/*", "Cargo.toml"]` line in `Cargo.toml`. Probably `README.md` ought to be added there.
