### ISSUE TITLE
Flexible child sizing issues

### ISSUE THREAD

**Issue by jihiggins** [DioxusLabs/taffy#224]
## `taffy` version

https://github.com/DioxusLabs/taffy/commit/d295d9b5a1de28fa6644a7a4d5fefcd3b6957773

## What you did

```
{
  "root": {},
  "container": {
    "size": {
      "width": {
        "Points": 800.0
      },
      "height": {
        "Points": 400.0
      }
    }
  },
  "container2": {
    "flex_direction": "Row",
    "flex_wrap": "Wrap",
    "align_content": "FlexStart",
    "align_items": "FlexStart",
    "flex_grow": 1.0
  },
  "window": {
    "size": {
      "width": {
        "Points": 50.0
      },
      "height": {
        "Points": 50.0
      }
    }
  }
}
```

## What went wrong

![GIF 9-1-2022 11-38-33 AM](https://user-images.githubusercontent.com/9329131/187946124-93201cf1-c825-401e-bfa4-4c19bff7165b.gif)

The nodes are setup as

Root[Container[Container2[window, window, window, ...], Container2]]

(Root is just set to the size of the screen.)

I would expect both Container2 nodes to only take up half of Container's max_width, but it seems like the Container2 nodes end up getting a max_width equal to Container.max_width. The children in the Container2 node seem to break the flex_grow/flex_basis settings. It seems like they maybe aren't really accounting for siblings when determining their max_width?

This is what happens with `flex_basis: Percent(0.5)` on the Container2 instances:
![unknown](https://user-images.githubusercontent.com/9329131/187946684-07317850-2665-4291-9c6f-3fd0a379f6d8.png)

If nothing else, it seems like it shouldn't have anything completely shifted out of the bounds of the top level Container node.

The only settings I've found that don't have this problem are when I just set the "size" for the Container2 nodes to the correct values manually.

**Comment by nicoburns** [comment]
@jihiggins Have you tried reproducing this in a browser? I think this is just how Flexbox works. In particular, the flex basis will be floored by the minimum content sizes of the children. A flex basis of `0.5` does *not* mean take up 50% of the container. The obvious way to style this would be to set `max_width: 50%` (or `width: 50%`) on the children.

**Comment by jihiggins** [comment]
I ended up figuring this out eventually. Sorry, forgot what the solution was / to close this ticket ;/    but iirc it was just user-error. Thanks!

**Comment by nicoburns** [comment]
@jihiggins Excellent :) I thought so, but it's easy for me to think that and I didn't want to dismiss your issue without investigating it properly!
