### ISSUE TITLE
Enable no_std option

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#23]
This is commonly desired within the games ecosystem, and if we can swing it, would be a good fit for a foundational crate like this.

**Comment by TimJentzsch** [comment]
I think this is already the case when the `std` feature is disabled:
https://github.com/DioxusLabs/stretch/blob/c267e6296caea4217a498935ccaf57483b5c9235/src/lib.rs#L1

**Comment by alice-i-cecile** [comment]
Yep, checks out. Looks like it was added in https://github.com/vislyhq/stretch/issues/10

**Comment by mockersf** [comment]
CI tests for `no_std` should be added
