### ISSUE TITLE
Enable Hacktoberfest

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#235]
## What problem does this solve or what need does it fill?

Hacktoberfest is an ongoing event that encourages people to contribute to open source projects.
Since taffy is a bit low on contributors, but not too hard to get into, this might be a nice opportunity for us to get more help.

## What solution would you like?

Opt into Hacktoberfest. I believe we need to add the `hacktoberfest` topic to the repository on GitHub.

## What alternative(s) have you considered?

Don't opt in. This can also have some downsides, such as low effort contributions that just aim to get the rewards.

## Additional context

- [Hacktoberfest website](https://hacktoberfest.com/)

**Comment by alice-i-cecile** [comment]
> I believe we need to add the hacktoberfest topic to the repository on GitHub.

Can you find the details here? I couldn't immediately find this on the site.

**Comment by nicoburns** [comment]
> Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.
> Choose issues that have a well-defined scope and are self-contained.

Looks like you also need to label issues you want people to submit PRs for.

**Comment by alice-i-cecile** [comment]
> Looks like you also need to label issues you want people to submit PRs for.

This one appears to be optional :) Marking merged PRs should also not be needed, since we're not using bors. Added the label.
