### ISSUE TITLE
Slow performance with deep hierachies

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/taffy#243]
## `taffy` version

Tested with latest main (`e5b721cd225a306635ec3133ef154ea60ac37a39`), but I believe this affects all versions of taffy.

## Platform

Rust/macOS

## What you did

I was interested to see how realistic the benchmarks were. In particular, the "big tree (100_000 nodes)/deep hierarchy" benchmark seemed unacceptably slow clocking in at around 2 seconds relatively fast M1 MacBook. However, 100,000 nodes seemed quite extreme I therefore decided to try a more realistic node count.

In order to determine what a realistic node count might be, I surveyed a few different web apps for both the total number of nodes and the maximum depth. The results were:

- Total number of nodes was generally between 3000 and 8000
- Max depth was generally between 14 and 34

**I therefore updated the above benchmark to use a lower total node count of 10,000, but a branch factor (number of children per node) of 2 rather than 7. This leads to a depth of 14**

## What went wrong

In this configuration, taffy took **17.306s** to run. Which is of course much *slower* than the shallower benchmark with 10x more nodes.

## Additional information

I suspect this still isn't an entirely realistic benchmark, as it was not possible to set the branching factor low enough to match both the number of nodes and the depths I observed on websites (for example this github page I'm writing in now has a depth of 25 with only ~1300 total nodes), and it's possible that styles such as "width: 100%" are reducing the impact of depth in some cases. Nevertheless, I would expect most real-life layouts to have a depth of greater than 6.

Uses benchmarks from https://github.com/DioxusLabs/taffy/pull/165

**Comment by alice-i-cecile** [comment]
Yep, there appears to still be an exponential time performance issue with depth :( This was expected from our very start of this library (off of `stretch`), and we haven't tracked it down yet.

**Comment by alice-i-cecile** [comment]
Excellent work on tracking down better numbers for those benchmarks BTW! Love to see a data-informed approach.

Could you open a PR to tweak those settings in the benchmarks?

**Comment by nicoburns** [comment]
> Could you open a PR to tweak those settings in the benchmarks?

I can do, but I wasn't sure if we wanted to slow the benchmarks down so much. A single run would be 17s, but the benchmarks run it several times, so I think it's 3-4mins runtime in total.

**Comment by nicoburns** [comment]
This could potentially be an interesting benchmark: https://cdpn.io/pen/debug/kQMYgp (from https://developer.chrome.com/blog/flexbox-layout-isn-t-slow/)

**Comment by alice-i-cecile** [comment]
> A single run would be 17s, but the benchmarks run it several times, so I think it's 3-4mins runtime in total.

Hmm, I think I prefer "realistic" over "fast" :)

**Comment by nicoburns** [comment]
In somewhat of a stroke of luck (I was hoping to get performance improvements with this change, but not this good), I think I've actually managed to at least partially solve the issue:

I'm now getting (node count/depth):

- ~3ms for the 10,000/14 case (was 17 seconds)
- ~4ms for the the original 100,000/7 benchmark (was 5 seconds)
- Although it's still 10 seconds for 100,000/17

That last one is still quite slow, but that does seem like a lot of nodes. I would like to try and test something like 10,000/30 if I can, but that will require rejigging to the test generator to work differently, and I think we may better creating a fully realistic benchmark based off a real webpage somewhere.

The change, by the way, was to up the numbers of cache slots to 4, and to assign cache slot based on which dimensions have already been calculated (none, width, height, or both).

(Side note: this is on top of a branch that already somewhat improves things compared to main which it turns out I was benching on before. The 10,000/14 benchmark which was taking 17 seconds on this branch actually takes 45 on main!)

PRs to follow.

**Comment by nicoburns** [comment]
Full benchmarks:

| Benchmark | main (w/new benchmarks) | lat/layout-algo-trait branch | % change | 
| --- | --- | --- | --- |
| big trees/10_000 nodes (2-level hierarchy) | 44.472 µs | 45.272 µs | no change |
| big trees/100_000 nodes (2-level hierarchy) | 4.2695 ms | 4.5856 ms | no change |
| big trees/100_000 nodes (7-level hierarchy) | 2.8302 s | 4.2983 ms | -99.738% |
| big trees/4000 nodes (12-level hierarchy)) | 10.988 s | 17.138 µs | -100.000% |
| big trees/10_000 nodes (14-level hierarchy) | 46.336 s | 3.3227 ms | -99.992% |
| big trees/100_000 nodes (17-level hierarchy) | - | 10.998 s | - |
| deep hierarchy/build  | 701.74 ns | 696.26 ns | no change |
| deep hierarchy/single | 6.8114 µs | 6.3035 µs | no change |
| deep hierarchy/relayout  | 4.1475 µs | 2.2235 µs | -46.389% |
| generated benchmarks  | 206.40 µs | 208.63 µs | no change |

**Comment by alice-i-cecile** [comment]
I'm keen to try out some head to heads with yoga and the browser layout tools once this is all merged 😂
