### ISSUE TITLE
Tentative migration to taffy 0.2 failed

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#250]
## `taffy` version

Targetting ba4cd3c3b1b36f72434469312416814f82bea5ff

## What you did

Attempted to migrate Bevy to Taffy 0.2, via this [commit](https://github.com/bevyengine/bevy/commit/86b592943aff8fd0779c6fece729511bea1a30b5) in this [branch](https://github.com/rparrett/bevy/tree/taffy-2).

Then, run any UI example in Bevy.

## What went wrong

thread 'main' panicked at 'invalid SparseSecondaryMap key used', /Users/me/.cargo/git/checkouts/taffy-3438f0b42e7e0e0f/ba4cd3c/src/node.rs:207:13
   0: std::panicking::begin_panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:616:12
   1: <slotmap::sparse_secondary::SparseSecondaryMap<K,V,S> as core::ops::index::IndexMut<K>>::index_mut
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.6/src/sparse_secondary.rs:852:21
   2: taffy::node::Taffy::set_measure
             at /Users/me/.cargo/git/checkouts/taffy-3438f0b42e7e0e0f/ba4cd3c/src/node.rs:207:13
   3: bevy_ui::flex::FlexSurface::upsert_leaf
             at ./crates/bevy_ui/src/flex/mod.rs:110:13

## Additional information

Identified by @rparrett. 

>  it seems like set_measure is just not accounting for the case where there was no previous measure function?

**Comment by rparrett** [comment]
Bevy seems to generally work (~8% speedup for `many_buttons`) with

```diff
diff --git a/src/node.rs b/src/node.rs
index 6ee3f94..f2febf8 100644
--- a/src/node.rs
+++ b/src/node.rs
@@ -204,7 +204,15 @@ impl Taffy {
     pub fn set_measure(&mut self, node: Node, measure: Option<MeasureFunc>) -> TaffyResult<()> {
         if let Some(measure) = measure {
             self.nodes[node].needs_measure = true;
-            self.measure_funcs[node] = measure
+            match self.measure_funcs.entry(node).unwrap() {
+                slotmap::sparse_secondary::Entry::Occupied(mut entry) => {
+                    let func = entry.get_mut();
+                    *func = measure;
+                }
+                slotmap::sparse_secondary::Entry::Vacant(entry) => {
+                    entry.insert(measure);
+                }
+            }
         } else {
             self.nodes[node].needs_measure = false;
             self.measure_funcs.remove(node);
```

**Comment by Weibye** [comment]
>it seems like set_measure is just not accounting for the case where there was no previous measure function?

This is definitely the case. The below code panics exactly the same way:

```rs
    // It should be possible for a node to first have no measure function,
    // then at a later point get a measure func.
    fn no_measure_then_measure() {
        let mut taffy = Taffy::new();
        let node = taffy.new_leaf(FlexboxLayout::default()).unwrap();
        taffy.set_measure(node, Some(MeasureFunc::Raw(|_, _| Size { width: 200.0, height: 200.0 }))).unwrap();
        // taffy.compute_layout(node, Size::MAX_CONTENT).unwrap();
    }
```
