### ISSUE TITLE
Max size overrides min size, but the reverse should be true

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#261]
## `taffy` version

0.2

## What you did

```rust
use taffy::prelude::*;

fn main() {
    let mut taffy = Taffy::new();
    let child = taffy.new_leaf(
        Style {
            size: Size { 
                width: Dimension::Points(2.), 
                height: Dimension::Points(2.) 
            },                
            ..Default::default()
        }
    ).unwrap();

    let parent = taffy.new_with_children(Style {
            size: Size {
                width: Dimension::Points(1.), 
                height: Dimension::Points(1.)
            },
            ..Default::default()        
        }, &[child]
    ).unwrap();

    let _ = taffy.compute_layout(parent, Size {
        width: AvailableSpace::Definite(1.),
        height: AvailableSpace::Definite(1.),
    });

    println!("{:#?}", taffy.layout(child).unwrap().size);
}
```

Output:

```rust
parent size = Size { width: 1.0, height: 1.0 }
child size = Size { width: 1.0, height: 2.0 }
```

## What went wrong

As the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/max-width) state:

> max-width overrides [width](https://developer.mozilla.org/en-US/docs/Web/CSS/width), but [min-width](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width) overrides max-width

## Additional information

Migrated from https://github.com/bevyengine/bevy/issues/6737, as this is taffy's bug.

**Comment by geom3trik** [comment]
I think the example code may be incorrect, I don't see any reference to min or max size, just to size. The linked bevy issue however does use min and max size.

**Comment by geom3trik** [comment]
Okay I see that the example code is also in a comment in the linked bevy issue but this seems like something separate? Based on the original example in the linked issue I think a minimum reproducable example of the bug might be this:
```rust
use taffy::prelude::*;

fn main() -> Result<(), taffy::error::TaffyError> {
    let mut taffy = Taffy::new();

    let child = taffy.new_leaf(Style {
        size: Size { width: Dimension::Points(50.0), height: Dimension::Points(50.0) },
        min_size: Size {width: Dimension::Points(100.0), height: Dimension::Points(100.0)},
        max_size: Size {width: Dimension::Points(10.0), height: Dimension::Points(10.0)},
        ..Default::default()
    })?;

    taffy.compute_layout(
        child,
        Size { height: AvailableSpace::Definite(100.0), width: AvailableSpace::Definite(100.0) },
    )?;

    println!("child: {:#?}", taffy.layout(child)?);

    Ok(())
}
```
Which does indeed apply the max constraint over the min constraint. Correct me if I'm wrong though.

**Comment by TimJentzsch** [comment]
Yes, I think the first example code tests the parent being smaller than the child.
In this case I assume the behavior would depend on the `overflow` property, which I don't think we support at this point.
