### ISSUE TITLE
Make taffy::compute::compute_layout public

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/taffy#263]
The combination of #238 and #246 means that it is now almost possible to use taffy without using the `Taffy` struct at all. One can provide their own storage type implementing `LayoutTree` with it's own methods for constructing a tree. In theory, one should then be able to call `taffy::compute::compute_layout` directly on this type. Unfortunately this function isn't public which is currently preventing this use case.

I suggest that we make this method public (perhaps it would be best to re-export as a top-level function?). We may also want to document the existence of the `LayoutTree` trait.

**Comment by alice-i-cecile** [comment]
Yep, I'm on board!
