### ISSUE TITLE
Properly implement `Start`, `End`, `FlexStart`, and `FlexEnd` alignment variants

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/taffy#307]
When refactoring the alignment types to work with CSS Grid, I couldn't work out what the difference between `start`/`end` and `flex-start`/`flex-end` was. I came to the conclusion that they were just aliases of each other, and folded them into one. It turns out that this works for Grid, but it is wrong for Flexbox. The difference is:

- `flex-start`/`flex-end` are effected by `FlexDirection` (the `RowReverse` and `ColumnReverse` directions flip them.
- `start`/`end` are not effected by `FlexDirection`.

Currently we have variants called `Start` and `End` that behave like `FlexStart` and `FlexEnd`. We ought to add new variants for this use case, and alter start/end to work as per the spec.

This probably isn't hugely high priority unless someone complains about it because I doubt many people are using `RowReverse`/`ColumnReverse`.

**Comment by Weibye** [comment]
This is probably going to be more prominent of an issue once taffy starts supporting multiple writing directions and orientations.

That being said, we did use `RowReverse` a lot in Bevy since we had an inverse coordinate system until quite recently, which is not unthinkable that other users of Taffy do as well.

**Comment by nicoburns** [comment]
> This is probably going to be more prominent of an issue once taffy starts supporting multiple writing directions and orientations.

Actually, it's orthogonal to that. These properties are both effected by e.g. setting an `RTL` direction. But there's an additional level of indirection based on flex-direction for the flex-prefixed variants.

> That being said, we did use RowReverse a lot in Bevy since we had an inverse coordinate system until quite recently

Ah, in that case we probably ought to fix this prior to releasing `0.3`.

**Comment by Weibye** [comment]
> > That being said, we did use RowReverse a lot in Bevy since we had an inverse coordinate system until quite recently
> 
> Ah, in that case we probably ought to fix this prior to releasing `0.3`.

It was reverted in [this PR](https://github.com/bevyengine/bevy/pull/6000), and [released in Bevy 0.9](https://bevyengine.org/news/bevy-0-9/#bevy-ui-the-origin-is-now-in-the-top-left) so it might not be very pressing to solve this, at least not for Bevy's usage.

That being said, the nuances of these layout algorithms are so complex that any time we can improve the "strictness" and clarity of the various types and how to use them makes the crate so much easier to work with.

**Comment by alice-i-cecile** [comment]
Yeah, I'd like to fix this before the release.
