### ISSUE TITLE
new_leaf causes memory leak

### ISSUE THREAD

**Issue by dzhou121** [DioxusLabs/taffy#359]
My app removes and create new node very often. And taffy memory seems to keep increasing. 

Can I ask what's the purpose for these 2 lines? 

```
        let _ = self.children.insert(new_vec_with_capacity(0));
        let _ = self.parents.insert(None);
```

**Comment by nicoburns** [comment]
> Can I ask what's the purpose for these 2 lines?

That records the parent-child relationship between nodes so that they form a tree which can be laid out. These will be mutated if you call `set_children` or similar on the node.

> My app removes and create new node very often.

Do the nodes you are removing have children? If they do then you need to recusively remove the children too. Also, do they have measure_funcs? Looks like a node's measure_func doesn't get removed until a new node gets assigned to it's slot in the slotmap, and then only if the new node has a measure_func.

> And taffy memory seems to keep increasing.

How much memory is it using? Can you create sample code that reproduces the issue? To a limited extent I would expect this, but if it *keeps* going up then something's not right.

**Comment by dzhou121** [comment]
In my profiling, it's the slotmap which keeps growing. I think it's because the key is never removed from the slotmap after inserting.

**Comment by nicoburns** [comment]
I am unable to reproduce this. The following snippet runs with steady RAM usage for me for when running it for over 5 minutes: it does creep up periodically, but then it comes back to down again (and it never goes up that much). Measured with htop (how are you measuring RAM usage?).

```rust
use taffy::prelude::*;
use taffy:: node::Measurable;
use taffy::node::MeasureFunc;

fn main() -> Result<(), taffy::error::TaffyError> {
    let mut taffy = Taffy::new();

    let parent = taffy.new_leaf(Style::default())?;

    loop {
        let children : Vec<Node> = (0..10000).map(|_| {
            let string = "FOOBAR".to_string();
            let measure = MeasureFunc::Boxed(Box::new(move |_, _| {
                let bar = string.len();
                Size { width: bar as f32, height: bar as f32 }
            }) as Box<dyn Measurable>);
            taffy.new_leaf_with_measure(Style::default(), measure).unwrap()

        }).collect();
        taffy.set_children(parent, &children)?;
        taffy.compute_layout(parent, Size::max_content())?;
        println!("parent size: {:#?}", taffy.layout(parent)?);
        println!("Children len {}", children.len());
        children.iter().for_each(|child_id| {
            taffy.remove(*child_id).unwrap();
        });
    }
}
```

As you can see, the `remove` method does remove those references (it doesn't remove measure_funcs but this doesn't cause a permanent leak as `self.measure_funcs` is a `SecondarySparseMap`):

```rust
    pub fn remove(&mut self, node: Node) -> TaffyResult<Node> {
        if let Some(parent) = self.parents[node] {
            if let Some(children) = self.children.get_mut(parent) {
                children.retain(|f| *f != node);
            }
        }

        let _ = self.children.remove(node);
        let _ = self.parents.remove(node);
        let _ = self.nodes.remove(node);

        Ok(node)
    }
```

**Comment by dzhou121** [comment]
Sorry my bad. I was missing removing a child in my code. Thanks for looking into it for me.
