### ISSUE TITLE
Unable to test `taffy` locally due to missing libclang library

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#428]
## `taffy` version

0596475afda99229de96976e73b2d637c78fdb8b and up to current main

## Platform

Windows 11 Pro

## What you did

run `cargo test` 

## What went wrong

Got an error saying that I'm missing libclang:

```
 --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\<user>\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.63.0\./lib.rs:2338:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional Information

#337 introduced `yoga` as a dev-dependency. All commits before that works fine.

## Proposed Change

The _bug_ here is that there should be a note in `CONTRIBUTING.md` if development of the crate depends on specific installed software like what we have with `chromedriver` for the gentests.

Alternatively construct our development environment in a way that does not rely on external software, but unsure if that is desired or possible.

**Comment by nicoburns** [comment]
Hmm... yoga is only used for benchmarks. I wonder if we could make benchmarks a separate crate and remove the need to compile it just for tests. Otherwise, yes just documenting the need for a C compiler makes sense. The `yoga` dependency really ought to be optional, but unfortunately cargo doesn't support optional dev dependencies yet https://github.com/rust-lang/cargo/issues/1596

**Comment by Weibye** [comment]
> make benchmarks a separate crate and remove the need to compile it just for tests

That setup would behave more akin to the current `gentest`, where its out of the way for anyone contributing until they specifically need to engage with that part of the code.

**Comment by Weibye** [comment]
I just noticed it is also preventing me from running any examples 🙃

**Comment by nicoburns** [comment]
Hmm... I definitely think we ought to make benchmarks their own crate. It's just not acceptable for people to need a C compiler to run tests or examples. It'll make running benchmarks *slightly* less convenient (I don't think we'll be able to hook it up to `cargo bench`). But that's not really a big deal.
