### ISSUE TITLE
Simplify public module hierarchy

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/taffy#435]
## What problem does this solve or what need does it fill?

When a user browses the docs for Taffy, it can be confusing to know where to look as there are a lot of modules, some of which are much more important than others

## What solution would you like?

- Make `math` module private: it has no public items anyway.
- Make the `error` module private and re-export `TaffyError`/`TaffyResult` as top-level types instead.
- Merge `axis` module into `geometry`
- Merge `tree`, `node`, `data`, `layout` and `cache` modules into the `tree` module:
   - `LayoutTree`, `RunMode`, `SizingMode`,`SizeAndBaselines` and `Layout` should live in the top-level `tree` module
   - `NodeId`, `NodeData`, and `MeasureFunction` should live in `tree::node`
   - `cache` should remain it's own module, just nested under `tree`
   - `Taffy` should live it's own `taffy_tree` module
   - All public types in `tree` should rexported from the top-level `tree` module
- `Taffy` should be renamed to `TaffyTree`

## What alternative(s) have you considered?

Don't do this.

## Additional context

<img width="990" alt="Screenshot 2023-04-11 at 14 30 38" src="https://user-images.githubusercontent.com/1007307/231178471-ea54822b-cb45-4aa4-bd51-0e15b8cca294.png">

**Comment by Weibye** [comment]
I'm in favour of the proposed structure. :+1|
