### ISSUE TITLE
Update benchmark HTML report generation

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#44]
## What problem does this solve or what need does it fill?

When running `cargo bench`, I get the following warning:

```
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.
```

## What solution would you like?

As explained in the warning, we need to either switch to `cargo-criterion` or enable the `html_reports` feature in our `Cargo.toml`.

**Comment by nicoburns** [comment]
We're already using criterion 0.4 now, so I don't think this issue is relevant anymore.
