### ISSUE TITLE
Split test fixtures into different folders per algorithm

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/taffy#479]
> What do you think about splitting the `test_fixtures` (and corresponding generated files) into multiple folders?
I think one folder per algorithm and maybe one for mixed tests would be useful to organize things a bit.
I'm not sure how hard that would be to integrate in the generation script though.

_Originally posted by @TimJentzsch in https://github.com/DioxusLabs/taffy/pull/474#pullrequestreview-1422130774_

This would give us the following folders:

- `flex`
- `grid`
- `block`
- `leaf`
- `gridflex`
- `blockflex`
- `blockgrid`

Note:`grid`, `block` and `leaf` algorithm tests are prefixed with `grid`/`block`/`leaf`. The remaining unprefixed tests are all flexbox tests. We would likely also need to reorganise the generated tests themselves a little. Perhaps by nesting them in modules corresponding to the directory they originate in.

**Comment by aemreaydin** [comment]
I would like to work on this issue. This is going to be my first issue on taffy but I think I have a simple understanding of what needs to be done here.

1) Move files prefixed with the given categories (flex, grid, etc.) in test_fixtures into their respective categories. Unprefixed ones can go into the flex folder.
2) Update the gentest code to respect the file structure when generating the tests.

**Comment by alice-i-cecile** [comment]
Sounds great: let us know if you have any questions :)

**Comment by aemreaydin** [comment]
Sounds good, that's what I was thinking as well. Will let you know if I have quetsions.

**Comment by aemreaydin** [comment]
Two questions;
1) Should I keep the files prefixed with "x" in the test_fixtures folder?
2) To recursively work with the directory, can I add the walkdir crate?

**Comment by nicoburns** [comment]
> Should I keep the files prefixed with "x" in the test_fixtures folder?

Yes. These are tests that are temporarily disabled, but that we hope to be enable later. They should be grouped under the directory that would be in if they didn't have the `x` prefix, but the `x` prefix should be retained

> To recursively work with the directory, can I add the walkdir crate?

Yes, that's fine :)
