### ISSUE TITLE
Strange layout behaviour with minWidth & flexDirection: row

### ISSUE THREAD

**Issue by ammarahm-ed** [DioxusLabs/taffy#507]
Hey @nicoburns, as you may already know we at @NativeScript have been trying to implement Taffy for android and ios through [nativescript-mason](https://github.com/triniwiz/nativescript-mason/) however we have encountered a strange issue with layout when using taffy which I will try to explain to you in the best possible way.

When `minWidth` value is set on a node & it's parent has `flex-direciton: row`, the value of `width` gets ignored completely. For example:

```js
<flex style={{flexDirection: "row"}}> // Switching to "column" fixes the problem.
    <button
          text="hello"
          style={{
            height: 200,
            width: 200,
            minWidth: 100,
            minHeight: 100,
          }}
        />
</flex>
```
results in width of the button being just `100` instead of `200`.

1.  Measure Function on android returns the correct width/height values for the problematic Views to Taffy:

![Screenshot_2023-04-02_at_12 50 57_PM](https://github.com/DioxusLabs/taffy/assets/40239442/8af099a7-d9ce-45be-ba69-db90dcb4b357)

2.     Layout of the parent View is also correct:
![Screenshot_2023-04-02_at_12 51 40_PM](https://github.com/DioxusLabs/taffy/assets/40239442/d3f8537a-56d9-4157-b212-a4d343ac7ac3)

3.  But when applyRecursiveLayout gets called on the Button in this case, the width value in `node.layout` is 0 (or the minWidth value) while height is 700.
![Screenshot_2023-04-02_at_12 52 01_PM](https://github.com/DioxusLabs/taffy/assets/40239442/9cec4448-b00f-4070-9ef8-66c21921e97e)

4.  Setting minWidth to 0 results in View having 0 width instead of using the value as a minimum constraint only.

I am unable to reproduce this behaviour with taffy itself directly in rust. On android, the issue doesn't happen if layout is provided through xml so it's predefined. However when for example you layout a view later on, or add a button etc from Java, the issue appears.

For example here I am changing the button size after first layout and render. The button's width is 300f when it should. be 1100f instead in final layout.
```java
val flexBtnNode = binding.flexRoot.nodeForView(binding.btn)

    flexBtnNode.configure {
      NodeHelper.setSizeWidth(flexBtnNode, Dimension.Points(1100f))
    }

    flexBtnNode.configure {
      NodeHelper.setMinSizeWidth(flexBtnNode, Dimension.Points(300f))
    }

    flexBtnNode.configure {
      NodeHelper.setMaxSizeWidth(flexBtnNode, Dimension.Points(1200f))
    }
```
The issue can be reproduced on the nativescript-mason repo https://github.com/triniwiz/nativescript-mason/

Taffy version is `taffy = { version = "0.3.12" }`

**Comment by nicoburns** [comment]
@ammarahm-ed Are you calling https://docs.rs/taffy/latest/taffy/node/struct.Taffy.html#method.mark_dirty after updating the styles for the node (e.g. after adding the width). This is necessary in order to invalidate Taffy's cache.

If you are, then it would be helpful to have to a runnable reproduction. One that uses `nativescript-mason` would be acceptable if you can't reproduce it using pure Rust.

**Comment by ammarahm-ed** [comment]
@nicoburns We do call `mark_dirty` every time styles are updated. All other style properties work normally like flexDirection/justify-content etc except width (which doesn't work only when minWidth is set).

I will provide you with a runnable reproduction for android.

**Comment by ammarahm-ed** [comment]
Hey I was able to fix the issue. It seemed that we were not using `Dimension::Auto` for `flex_basis` which caused the bug.
