### ISSUE TITLE
`basic` example alternative `Size::NONE` is not actually compiling

### ISSUE THREAD

**Issue by hasezoey** [DioxusLabs/taffy#523]
## `taffy` version

dab541d6104d58e2e10ce90c4a1dad0b703160cd

## Platform

anything that compiles rust (in my case `stable-x86_64-unknown-linux-gnu`)

## What you did

try to use the alternative mentioned in the `basic` example
https://github.com/DioxusLabs/taffy/blob/dab541d6104d58e2e10ce90c4a1dad0b703160cd/examples/basic.rs#L25-L26

## What went wrong

what were you expecting?:
to compile correctly

what actually happened?:
error

```txt
mismatched types
expected struct `taffy::geometry::Size<AvailableSpace>`
   found struct `taffy::geometry::Size<Option<f32>>`
```

**Comment by nicoburns** [comment]
This ought to be `Size::MAX_CONTENT` in latest Taffy. Perhaps we also ought to uncomment this code to prevent bitrot like this in future.
