### ISSUE TITLE
Implement z-index support

### ISSUE THREAD

**Issue by vkurchatkin-miro** [DioxusLabs/taffy#565]
## What problem does this solve or what need does it fill?

Not sure if something like this is in scope of Taffy it would be definitely very useful. 

## What solution would you like?

I would like to have Web-like (or conformant) `z-index` support.  That is not a simple thing and a bit convoluted but a very powerful feature. On the API level that would require adding a new style property and some sort of iterator to iterate over all of the nodes using calculated order.

## What alternative(s) have you considered?

Implementing it outside of taffy is definitely possible.

**Comment by alice-i-cecile** [comment]
Agreed: I think this is better handled by downstream crates.

**Comment by vkurchatkin-miro** [comment]
@geom3trik well, it is related to rendering pretty much the same way as layout. You could think about it as layout along the third axis. Taffy already has `order` is its layout, but it seems pretty much useless currently
