### ISSUE TITLE
It's not obvious that only nodes with context get their measure function called (Not sure if this is a bug)

### ISSUE THREAD

**Issue by reivilibre** [DioxusLabs/taffy#597]
## `taffy` version

```toml
taffy = { git = "https://github.com/DioxusLabs/taffy.git", rev = "a2d9829807d7720ccbf8736cb1720e55bf2bbdbb" }
```
(current `main`; almost 0.4.0 from what I understand)

## Platform

Rust on Linux

## What you did

I based my example off `examples/measure.rs`

Because I have no need for extra context information, I replace the calls to `insert_leaf_with_context` to `insert_leaf`.

```rust
mod common {
    pub mod image;
    pub mod text;
}
use common::image::{image_measure_function, ImageContext};
use common::text::{text_measure_function, FontMetrics, TextContext, WritingMode, LOREM_IPSUM};
use taffy::prelude::*;

enum NodeContext {
    Text(TextContext),
    Image(ImageContext),
}

fn measure_function(
    known_dimensions: taffy::geometry::Size<Option<f32>>,
    available_space: taffy::geometry::Size<taffy::style::AvailableSpace>,
    node_context: Option<&mut NodeContext>,
    font_metrics: &FontMetrics,
) -> Size<f32> {
    eprintln!("measure {known_dimensions:?}, {available_space:?}");
    if let Size { width: Some(width), height: Some(height) } = known_dimensions {
        return Size { width, height };
    }

    match node_context {
        None => Size::ZERO,
        Some(NodeContext::Text(text_context)) => {
            text_measure_function(known_dimensions, available_space, &*text_context, font_metrics)
        }
        Some(NodeContext::Image(image_context)) => image_measure_function(known_dimensions, image_context),
    }
}

fn main() -> Result<(), taffy::TaffyError> {
    let mut taffy: TaffyTree<NodeContext> = TaffyTree::new();

    let font_metrics = FontMetrics { char_width: 10.0, char_height: 10.0 };

    let text_node = taffy.new_leaf(
        Style::default(),
    )?;

    let image_node = taffy
        .new_leaf(Style::default())?;

    let root = taffy.new_with_children(
        Style {
            display: Display::Flex,
            flex_direction: FlexDirection::Column,
            size: Size { width: length(200.0), height: auto() },
            ..Default::default()
        },
        &[text_node, image_node],
    )?;

    // Compute layout and print result
    taffy.compute_layout_with_measure(
        root,
        Size::MAX_CONTENT,
        // Note: this closure is a FnMut closure and can be used to borrow external context for the duration of layout
        // For example, you may wish to borrow a global font registry and pass it into your text measuring function
        |known_dimensions, available_space, _node_id, node_context| {
            measure_function(known_dimensions, available_space, node_context, &font_metrics)
        },
    )?;
    taffy.print_tree(root);

    Ok(())
}
```

When I did this (to try and track down a problem in my application), I noticed that the measure function is never called (and for my application, the layout therefore seems all wrong)

```
TREE
└──  FLEX COL [x: 0    y: 0    w: 200  h: 0    content_w: 0    content_h: 0    border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967299))
    ├──  LEAF [x: 0    y: 0    w: 200  h: 0    content_w: 0    content_h: 0    border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967297))
    └──  LEAF [x: 0    y: 0    w: 200  h: 0    content_w: 0    content_h: 0    border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967298))
```

## What went wrong

- what were you expecting?
    - for the measure function to be called on at least the leaves, especially since the context parameter in the measure function is an `Option<...context...>`
- what actually happened?
    - because the measure function is not called, I get some layout with zeroes in, which may or may not be a bug but it's not what I expected from the documentation and intuition at least.

**Comment by nicoburns** [comment]
Agree that this is confusing. It made more sense for it to work this way when it was a measure function being set on each node. I think we could just change it to always run the measure function on leaf nodes. Although an empty flexbox (or grid) node is perfectly valid, and that's effectively what's being implemented here.

Another option would be to create a new `Display` variant for measured functions (e.g. `Display::Measure`) and use that to control whether the measure function runs. Perhaps that would be clearer and more explicit?

**Comment by reivilibre** [comment]
I suspect your intuition will be best for the best way to resolve this! (if the current design makes sense to you, it's possibly just a matter of documentation).
(...However in that case I would ask what the point of the context parameter in the measure function being an `Option<>` is.)

In my case, all my components use the `taffy::NodeId` (well, actually a `slotmap::DefaultKey`) as their primary key and the 'context' for the components is stored separately in various `(Sparse)SecondaryMap`s.

For my use case I am mostly interested in minimising memory overhead, so the idea of just always measuring leaves seems to make sense for me, but I can't say what applies for other users of the library. :)

`Display::Measure` does sound like an interesting approach. Am I right in saying that it only makes sense for leaves to have `measure` called?

**Comment by nicoburns** [comment]
I'm inclined to agree that just always calling the measure function for leaves make sense. If users want the size to be zero when the context is `None` then they can implement that logic themselves. I reckon we should make that change and we can revisit a `Display`-based approach in future.

> `Display::Measure` does sound like an interesting approach. Am I right in saying that it only makes sense for leaves to have measure called?

Yes. If there was a `Display::Measure` then it would effectively make those nodes leaf nodes as their children would be ignored. It would also be possible to add something like a `Display::Custom` that allows for fully custom layout for nodes (including the possibility of them having children), but that would need to be implemented and an API worked out.
