### ISSUE TITLE
Measure example wrapping calculation bug

### ISSUE THREAD

**Issue by joshka** [DioxusLabs/taffy#628]
## `taffy` version
0.4.0

## Platform

Rust / macOS

## What you did

- Took the measure example and ported it to ratatui as an example in https://github.com/joshka/tui-brulee
- Removed font metrics and vertical text
- Rendered the text rather than just the dimensions of the layouts

## What went wrong

Wrapped text doesn't quite fill the space and chops the final word(s) due to missing a +1 for the space between words.

If it's not clear:

- what were you expecting? - fully filled words in the space
- what actually happened? - words missing

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots

<img width="976" alt="image" src="https://github.com/DioxusLabs/taffy/assets/381361/283cf56a-4c9c-4f94-9c44-73f0b6211d9a">

<img width="1840" alt="image" src="https://github.com/DioxusLabs/taffy/assets/381361/5c52ab94-5bb0-40d6-9636-418284f38b4f">

My guess is that because this is example code, this doesn't matter all that much, but anyone copying out that code is going to run into the same bugs. I suspect the fix for this is 1 or two lines (or alternatively use [textwrap](https://crates.io/crates/textwrap)).

Note, I'm just exploring how this might fit into Ratatui at the moment - this might end up outside of Ratatui as a helper crate or inside as a new layout module. I'm not sure yet.

**Comment by nicoburns** [comment]
> Wrapped text doesn't quite fill the space and chops the final word(s) due to missing a +1 for the space between words.

Ah, this will be because the text measure function used in the examples was ported from the measure function we use for generated tests, and in our generated tests we are using zero-width-space (`U+200B`) characters which actually don't take up any space. As you say it's only example code, but I agree that this ought to be fixed to be a little smarter.

**Comment by joshka** [comment]
Ah that makes sense. Thanks for the quick reply :)
