### ISSUE TITLE
Documentation for `dirty` and `mark_dirty` Incorrect

### ISSUE THREAD

**Issue by GroveDG** [DioxusLabs/taffy#634]
## `taffy` version

0.4.1

## Platform

Documentation

## What went wrong

The `mark_dirty` and `dirty` functions on `TaffyTree` refer to marking _children_ as outdated, but `mark_dirty` marks _parents_ (and so on) as outdated.

## Additional information

It could also be that the documentation is what it's supposed to do and the code is wrong. I'm not sure.

**Comment by nicoburns** [comment]
Pretty sure the docs are wrong here as you suspected. I reckon `mark_dirty` ought to be "node and it's parents/ancestors" and `dirty` probably ought to just say "the node" and not talk about parents/children at all.
