### ISSUE TITLE
Generic over NodeId

### ISSUE THREAD

**Issue by cksac** [DioxusLabs/taffy#763]
## What problem does this solve or what need does it fill?
I have a tree represented by key of (u64, u64), currently NodeId restricted to u64.
The layout algorithm is able to generic to NodeId, due to readability and compile time and most cases use u64 is enough, now set to u64. 

## What solution would you like?
Change NodeId as associated type / Generic parameter.

## What alternative(s) have you considered?
I have squeeze the key to u64 in my lib, but it won't work out.

## Additional context
The library I am working on is [compose-rt](https://github.com/cksac/compose-rt) which is tree management lib.
I want to implement Layout Tree abstraction using compose-rt, https://github.com/cksac/compose-taffy (now it depends on compose-rt v0.13.0 with u64 as key, which can't support component like this [example ](https://github.com/cksac/compose-rt/blob/main/examples/test.rs) which use (u64, u64) as key now.

**Comment by nicoburns** [comment]
Hmm... we could do this, but it'll be a bit awkward (and bad for compile times) to have all the algorithm code generic. What do the two u64 components of your IDs represent? (/why do you need such a large node id?). Note that it is possible to handle arena allocation by storing the arena pointer in the `impl PartialLayoutTree` type.

Taffy won't layout trees with more than about 100k nodes performantly, so in my mind the only case in which 64 bits should be required is if the `NodeId` is a pointer (for Taffy's built-in tree, the NodeId is composed of a 32bit index and a 32bit generational version). But I am open to hearing more about your use case.

**Comment by cksac** [comment]
The node id in my lib is the the unique of call trace, using source location and a u32 key if it is in a loop.
single u64 represent (first 32 bit: offset to an anchor source location, last 32 bit: a key id if it is in loop)
Then node id is represent as (parent, current)

this [example](https://github.com/cksac/compose-rt/blob/main/examples/mini_demo.rs) show the key idea
```rust
Root
└──  14637248544768      : Some( examples\mini_demo.rs:89:7 )
    ├──  18446734521702285312: Some( examples\mini_demo.rs:90:9 )
    │   ├──  18446734624781500416: Some( examples\mini_demo.rs:82:19 ) // the id actually is (18446734521702285312, 18446734624781500416)
    │   └──  18446734624781500417: Some( examples\mini_demo.rs:82:19 ) 
    └──  18446734418623070208: Some( examples\mini_demo.rs:91:9 )
        ├──  18446734624781500416: Some( examples\mini_demo.rs:82:19 ) // the id actually is (18446734418623070208, 18446734624781500416)
        └──  18446734624781500417: Some( examples\mini_demo.rs:82:19 )
```

**Comment by nicoburns** [comment]
Interesting. The first bit makes sense, but why do you need `parent` in the ID?

**Comment by cksac** [comment]
without parent in the id, the 2nd component instance child will gone, as they are same in source, e.g. same key in HashMap now.

 the result will be like this. 
```rust
Root
└──  14637248544768      : Some( examples\mini_demo.rs:89:7 )
    ├──  18446734521702285312: Some( examples\mini_demo.rs:90:9 )
    │   ├──  18446734624781500416: Some( examples\mini_demo.rs:82:19 )
    │   └──  18446734624781500417: Some( examples\mini_demo.rs:82:19 ) 
    └──  18446734418623070208: Some( examples\mini_demo.rs:91:9 )
```

**Comment by nicoburns** [comment]
I think you need something like in the [custom_tree_owned_partial](https://github.com/DioxusLabs/taffy/blob/main/examples/custom_tree_owned_partial.rs#L149) example. Notice that the `tree`/`node` parameter passed into `compute_flexbox_layout` (and similar functions) is different each time it is called. That parameter effectively points to the `parent`, and child `NodeId`s are resolved relative to that.

For your setup you could have a "view struct" over your node container. Something like:

```rust
struct TreeView {
     tree: &mut YourTypeHere,
     parent: u64,
}
```

And implement the Taffy traits for that type. When `compute_child_layout` is called you create a new `TreeView`, reborrowing the underlying tree and setting the `parent` id in the new view to the id of the child you are being asked to layout.

**Comment by cksac** [comment]
um..can't figure out how to implement [TraversePartialTree ](https://github.com/cksac/compose-taffy/blob/main/src/layout.rs#L154) for [TaffyTree](https://github.com/cksac/compose-taffy/blob/main/src/layout.rs#L132)  with your proposal.

**Comment by nicoburns** [comment]
> um..can't figure out how to implement [LayoutPartialTree](https://github.com/cksac/compose-taffy/blob/main/src/layout.rs#L319) for [TaffyTree](https://github.com/cksac/compose-taffy/blob/main/src/layout.rs#L132) with your proposal.

I think you need an additional `parent_id` field in your `TaffyTree` struct. Then you can combine that with the `current_id` you get from Taffy in the methods to look up the node (presumably from somewhere in your Composer?).

Each time you recurse in `compute_child_layout` you create a new `TaffyTree` with a different `parent_id`. Also, you shouldn't need a measure function if you're using the low-level API, as you can call into functions to measure leaf nodes, etc directly from `compute_child_layout`.

**Comment by choisioo** [comment]
um seems like the recurse call is not in my control, it is in `taffy::compute_hidden_layout`, etc. I might need to duplicate all these taffy-built-in helper functions?

**Comment by cksac** [comment]
um seems like the recurse call is not in my control, it is in taffy::compute_hidden_layout, etc. I might need to duplicate all these taffy-built-in helper functions?

**Comment by cksac** [comment]
I finally manage to solve the problem by introducing an mapping from original key and slotmap key and update the Node type in my lib. Thanks for the incredible work on this project!

```git
-- pub nodes: Map<ScopeId, Node<N>>,

++ pub nodes: SlotMap<NodeKey, Node<N>>,
++ pub scopes: Map<ScopeId, NodeKey>,
``` 
```rust
//#[derive(Debug)]
//pub struct Node<T> {
//    pub parent: ScopeId,
//    pub children: Vec<ScopeId>,
//    pub data: Option<T>,
//}

#[derive(Debug)]
pub struct Node<T> {
    pub scope: ScopeId,
    pub parent: NodeKey,
    pub children: Vec<NodeKey>,
    pub data: Option<T>,
}
```
